# Generated by Django 4.1.7 on 2023-02-25 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('proveedor', models.CharField(max_length=200)),
                ('precio', models.IntegerField()),
                ('img_url', models.URLField()),
                ('estado', models.CharField(max_length=20)),
                ('en_stock', models.IntegerField()),
            ],
            options={
                'db_table': 'PRODUCTO',
            },
        ),
    ]
