# Generated by Django 4.1.7 on 2023-02-27 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webbase', '0002_producto_categoria_alter_producto_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'CATEGORIA',
            },
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'SUBCATEGORIA',
            },
        ),
    ]
